-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 17:45:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventario_brm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventario_brm` ;

-- -----------------------------------------------------
-- Schema inventario_brm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario_brm` DEFAULT CHARACTER SET utf8 ;
USE `inventario_brm` ;

-- -----------------------------------------------------
-- Table `inventario_brm`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_brm`.`productos` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `producto_nombre` VARCHAR(100) NOT NULL,
  `producto_cantidad` INT NOT NULL,
  `producto_num_lote` VARCHAR(45) NOT NULL,
  `producto_fecha_vencimiento` DATE NOT NULL,
  `producto_precio` DOUBLE NOT NULL,
  PRIMARY KEY (`producto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario_brm`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_brm`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_nombre` VARCHAR(45) NOT NULL,
  `cliente_direccion` VARCHAR(45) NOT NULL,
  `cliente_telefono` INT NOT NULL,
  `cliente_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario_brm`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario_brm`.`pedido` (
  `pedido_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `pedido_fecha` DATE NOT NULL,
  `pedido_cantidad` INT NOT NULL,
  `pedido_total` DOUBLE NOT NULL,
  PRIMARY KEY (`pedido_id`),
  INDEX `fk_pedido_producto_idx` (`producto_id` ASC),
  INDEX `fk_pedido_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_pedido_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `inventario_brm`.`productos` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `inventario_brm`.`clientes` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
